apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: eks-platform-slack-alerts
  namespace: monitoring
  labels:
    alertmanagerConfig: eks-platform
spec:
  route:
    receiver: slack-notifications
    groupBy:
      - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h

  receivers:
    - name: slack-notifications
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook
            key: webhook-url
          channel: "#all-fintech-team-b"
          sendResolved: true
          title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
          text: |
            Alert: {{ .CommonLabels.alertname }}
            Severity: {{ .CommonLabels.severity }}
            Description: {{ .CommonAnnotations.description }}
